defaults:
  - agent: ddpg
  - override hydra/launcher: submitit_local

# mode
reward_free: false
# task settings
task: hopper_hop
obs_type: states # [states, pixels]
frame_stack: 3 # only works if obs_type=pixels
action_repeat: 1 # set to 2 for pixels
discount: 0.99
# train settings
num_train_frames: 125010
num_seed_frames: 4000
# eval
eval_every_frames: 1000
video_eval_every_frames: 10000
num_eval_episodes: 10
# pretrained
snapshot_ts: 100000
snapshot_base_dir: /scratch2/james2602/URLB/outputs_pretrain
#snapshot_test_dir : /home/james2602/URLB/url_benchmark/snapshot_test
#snapshot_base_dir: /home/james2602/URLB/url_benchmark/outputs_pretrain

# model-based settings
# 0.training setting
num_epoch: 125
num_steps_per_epoch: 1000
policy_update_per_step: 20
model_horizon: 1
# 1.ensemble model settings
num_networks: 7
num_elites: 5
pred_hidden_size: 200
reward_size: 1
use_decay: true
#2. predict env settings
env_name: hopper_hop
#3. replay buffer settings
rollout_batch_size: 100000
model_train_freq: 250
model_retain_epochs: 1
epoch_length: 1000
#4. sampler
max_path_length: 1000
#5. rollout
rollout_max_length: 15
rollout_min_length: 1
rollout_max_epoch: 150
rollout_min_epoch: 20

# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
batch_size: ${agent.batch_size}
nstep: ${agent.nstep}
update_encoder: false # can be either true or false depending if we want to fine-tune encoder
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: false
# wandb settings
use_wandb: false
wandb_project: url_benchmark
# experiment
experiment: exp


hydra:
  run:
    dir: scratch2/james2602/URLB/outputs_finetune/${task}/${agent.name}/snapshot_${snapshot_ts}/seed_${seed}/sf_dim_${agent.sf_dim}
  sweep:
    dir: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}/.slurm
